language: php
php:
    - '7.3'
install:
    - composer self-update
    - make install
script:
    - make lint test
services:
    - postgresql
before_script:
    - psql -c 'create database travis_ci_test;' -U postgres
migrate:
    - make migrate