language: php
php:
    - '7.3'
services:
    - postgresql
before_script:
    - cp .env.travis .env
    - mysql -e 'create database homestead_test;'
    - php artisan migrate --no-interaction
install:
    - composer self-update
    - make install
script:
    - make lint test
after_script:
  - php artisan queue:work

    