language: php
php:
    - '7.3'
services:
    - postgresql
before_script:
    - cp .env.travis .env
    - psql -c 'create database travis_ci_test;' -U postgres
    - php artisan migrate
install:
    - composer self-update
    - make install
script:
    - make lint test
    