language: php
php:
    - '7.3'
services:
    - postgresql
before_script:
    - psql -c 'create database travis_ci_test;' -U postgres
install:
    - composer self-update
    - make install
script:
    - make migrate
    - make lint test
    